import {test, expect} from '../../fixtures/test'

// Schema.org microdata attributes (itemscope, itemtype, itemprop) appear in
// course content copied from external educational resources or generated by
// content management tools. They add semantic meaning for search engines
// without changing visual rendering — but must survive round-trips.
test.describe('Schema.org microdata attributes (itemscope/itemprop)', () => {
  test.beforeEach(async ({page, rcePage}) => {
    await page.goto('/scenarios/basic')
    await rcePage.waitForEditor()
  })

  async function setAndGet(page: any, html: string): Promise<string> {
    return page.evaluate((content: string) => {
      // @ts-expect-error -- TinyMCE global
      window.tinymce.activeEditor.setContent(content)
      // @ts-expect-error -- TinyMCE global
      return window.tinymce.activeEditor.getContent()
    }, html)
  }

  test('itemscope/itemtype on div — text preserved', async ({page}) => {
    const content = await setAndGet(
      page,
      '<div itemscope itemtype="https://schema.org/Course"><h2 itemprop="name">Introduction to Algorithms</h2><p itemprop="description">A foundational course on algorithm design.</p></div>',
    )
    expect(content).toContain('Introduction to Algorithms')
    expect(content).toContain('A foundational course on algorithm design')
  })

  test('itemprop on multiple elements — all text preserved', async ({page}) => {
    const content = await setAndGet(
      page,
      '<div itemscope itemtype="https://schema.org/Person"><span itemprop="name">Dr. Jane Smith</span>, <span itemprop="jobTitle">Professor of Computer Science</span></div>',
    )
    expect(content).toContain('Dr. Jane Smith')
    expect(content).toContain('Professor of Computer Science')
  })

  test('nested itemscope — all text preserved', async ({page}) => {
    const content = await setAndGet(
      page,
      '<div itemscope itemtype="https://schema.org/EducationalOrganization"><span itemprop="name">State University</span><div itemprop="department" itemscope itemtype="https://schema.org/Organization"><span itemprop="name">Department of Physics</span></div></div>',
    )
    expect(content).toContain('State University')
    expect(content).toContain('Department of Physics')
  })

  test('itemprop on a link — link text preserved', async ({page}) => {
    const content = await setAndGet(
      page,
      '<div itemscope itemtype="https://schema.org/Article"><a itemprop="url" href="/articles/1"><span itemprop="headline">Understanding Recursion</span></a></div>',
    )
    expect(content).toContain('Understanding Recursion')
  })
})
