import {test, expect} from '../../fixtures/test'

// <picture> and <source> are HTML5 responsive image elements. Canvas
// content generated by modern authoring tools may include them.
// TinyMCE may strip or preserve <source>; the <img> fallback text
// (alt attribute) and surrounding paragraph text must always survive.
test.describe('<picture> and <source> responsive images', () => {
  test.beforeEach(async ({page, rcePage}) => {
    await page.goto('/scenarios/basic')
    await rcePage.waitForEditor()
  })

  async function setAndGet(page: any, html: string): Promise<string> {
    return page.evaluate((content: string) => {
      // @ts-expect-error -- TinyMCE global
      window.tinymce.activeEditor.setContent(content)
      // @ts-expect-error -- TinyMCE global
      return window.tinymce.activeEditor.getContent()
    }, html)
  }

  test('paragraph text around <picture> is preserved', async ({page}) => {
    const content = await setAndGet(
      page,
      '<p>Before.</p><picture><source srcset="img.webp" type="image/webp" /><img src="img.jpg" alt="Course diagram" /></picture><p>After.</p>',
    )
    expect(content).toContain('Before')
    expect(content).toContain('After')
  })

  test('<img> alt text inside <picture> is preserved', async ({page}) => {
    const content = await setAndGet(
      page,
      '<picture><source media="(min-width: 800px)" srcset="large.jpg" /><img src="small.jpg" alt="Responsive image" /></picture>',
    )
    expect(content).toContain('alt')
    expect(content).toContain('Responsive image')
  })

  test('<picture> with multiple sources — no crash', async ({page}) => {
    const content = await setAndGet(
      page,
      '<picture><source srcset="img.avif" type="image/avif" /><source srcset="img.webp" type="image/webp" /><img src="img.jpg" alt="Multi-format image" /></picture><p>Caption below</p>',
    )
    expect(content).toContain('Caption below')
    expect(typeof content).toBe('string')
  })

  test('content around <picture> with srcset-only img', async ({page}) => {
    const content = await setAndGet(
      page,
      '<p>See figure:</p><picture><img src="fallback.png" alt="Figure" srcset="1x.png 1x, 2x.png 2x" /></picture><p>End of figure.</p>',
    )
    expect(content).toContain('See figure')
    expect(content).toContain('End of figure')
  })
})
