# frozen_string_literal: true

#
# Copyright (C) 2015 - present Instructure, Inc.
#
# This file is part of Canvas.
#
# Canvas is free software: you can redistribute it and/or modify it under
# the terms of the GNU Affero General Public License as published by the Free
# Software Foundation, version 3 of the License.
#
# Canvas is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
# A PARTICULAR PURPOSE. See the GNU Affero General Public License for more
# details.
#
# You should have received a copy of the GNU Affero General Public License along
# with this program. If not, see <http://www.gnu.org/licenses/>.
#

require "rqrcode"
require "rotp"

class Login::OtpController < ApplicationController
  include Login::Shared
  include Login::OtpHelper

  before_action :require_password_session, except: [:send_verification]
  before_action :forbid_on_files_domain
  skip_before_action :require_password_reset
  skip_before_action :check_mfa_ips_and_user_agents, except: :destroy
  before_action :require_authenticated_user, only: [:send_verification]
  skip_before_action :require_user, only: [:send_verification]

  OTP_ALLOWED_DRIFT = 30
  OTP_ALLOWED_DRIFT_SMS = 300
  OTP_SEND_REQUEST_COST = 100

  def new
    # if we waiting on OTP for login, but we're not yet configured, start configuring
    # OR if we're not waiting on OTP, we're configuring
    if (session[:pending_otp] && !secret_key) ||
       (!session[:pending_otp] && !configuring?)
      session[:pending_otp_secret_key] = ROTP::Base32.random
      @first_reconfiguration = true
    end

    pending_otp_cc_id = session[:pending_otp_communication_channel_id]

    if pending_otp_cc_id
      @cc = @current_user.communication_channels.find(pending_otp_cc_id)
    elsif !configuring?
      @cc = @current_user.otp_communication_channel
    end

    send_otp unless configuring?

    respond_to do |format|
      format.html { add_meta_tag(name: "viewport", id: "vp", content: "initial-scale=1.0,user-scalable=yes,width=device-width") }

      format.json do
        json_response = {
          # OTP setup required
          otp_configuring: configuring?,
          # OTP sent and awaiting verification
          otp_sent: configuring? ? nil : session[:pending_otp].presence,
          # nil if OTP generated by authentication app
          pending_otp_communication_channel_id: pending_otp_cc_id
        }.compact_blank

        render json: json_response, status: :ok
      end
    end
  end

  def send_via_sms
    return render status: :bad_request, text: "can't change destination until you're logged in" unless configuring?

    if params[:otp_login].try(:[], :otp_communication_channel_id)
      cc = @current_user.communication_channels.sms.unretired.find(params[:otp_login][:otp_communication_channel_id])
      session[:pending_otp_communication_channel_id] = cc.id
    end
    if session[:pending_otp_secret_key] && params[:otp_login].try(:[], :phone_number)
      path = params[:otp_login][:phone_number].gsub(/[^\d]/, "").to_s
      cc = @current_user.communication_channels.sms.by_path(path).first
      cc ||= @current_user.communication_channels.sms.create!(path:)
      if cc.retired?
        cc.workflow_state = "unconfirmed"
        cc.save!
      end
      session[:pending_otp_communication_channel_id] = cc.id
    end
    send_otp(cc)

    redirect_to otp_login_url
  end

  def create
    # this action can be called to try to find a valid OTP by chance.  To prevent
    # abuse, we'll make this look like an expensive operation so it would
    # get quickly rate limited if hit repeatedly.  This should be about 1/4
    # of a maxed out bucket.
    increment_request_cost(150)

    verification_code = params[:otp_login][:verification_code].delete(" ")

    drift = OTP_ALLOWED_DRIFT
    # give them 5 minutes to enter an OTP sent via SMS
    drift = OTP_ALLOWED_DRIFT_SMS if session[:pending_otp_communication_channel_id] ||
                                     (!session[:pending_otp_secret_key] && @current_user.otp_communication_channel_id)

    if Canvas.redis_enabled?
      key = "otp_used:#{@current_user.global_id}:#{verification_code}"
      # atomic claim — only one concurrent request wins; replays hit force_fail
      force_fail = true unless Canvas.redis.set(key, "1", ex: 10.minutes, nx: true)
    end

    if (!force_fail && ROTP::TOTP.new(secret_key).verify(verification_code, drift_behind: drift, drift_ahead: drift)) ||
       @current_user.authenticate_one_time_password(verification_code)
      if configuring?
        @current_user.one_time_passwords.scope.delete_all
        @current_user.otp_secret_key = session.delete(:pending_otp_secret_key)
        @current_user.otp_communication_channel_id = session.delete(:pending_otp_communication_channel_id)
        @current_user.otp_communication_channel.try(:confirm)
        @current_user.save!
      end

      if params[:otp_login][:remember_me] == "1"
        now = Time.now.utc
        old_cookie = cookies["canvas_otp_remember_me"]
        old_cookie = nil unless @current_user.validate_otp_secret_key_remember_me_cookie(old_cookie)
        cookies["canvas_otp_remember_me"] = {
          value: @current_user.otp_secret_key_remember_me_cookie(now, old_cookie, request.remote_ip),
          expires: now + 30.days,
          domain: remember_me_cookie_domain,
          httponly: true,
          same_site: :none,
          secure: CanvasRails::Application.config.session_options[:secure],
          path: "/login"
        }
      end
      if session.delete(:pending_otp)
        successful_login(@current_user, @current_pseudonym, otp_passed: true)
      else
        add_mfa_verified_ip_and_user_agent
        respond_to do |format|
          format.html do
            flash[:notice] = t "Multi-factor authentication configured"
            redirect_to settings_profile_url
          end
          format.json { render json: { otp_configured: true }, status: :ok }
        end
      end
    else
      respond_to do |format|
        format.html do
          flash[:error] = t "Invalid verification code, please try again"
          redirect_to otp_login_url
        end
        format.json { render json: { error: t("Invalid verification code, please try again") }, status: :unprocessable_content }
      end
    end
  end

  def cancel_otp
    clear_pending_otp
    render json: { message: "Multi-factor authentication process has been cancelled." }, status: :ok
  end

  def send_verification
    # Only send if user has MFA configured
    unless @current_user.otp_secret_key.present?
      return render json: { error: t("mfa_not_configured", "Multi-factor authentication is not configured") },
                    status: :unprocessable_content
    end

    # Check if user has a communication channel for OTP (SMS or email)
    # If not, they're using an authenticator app and don't need OTP sent
    cc = @current_user.otp_communication_channel
    unless cc
      return render json: { otp_not_required: true }
    end

    # Rate limit this endpoint to prevent SMS/email spam abuse
    # Allow ~6 sends before hitting rate limit
    # Only increment cost when actually sending (not for authenticator app users)
    increment_request_cost(OTP_SEND_REQUEST_COST)

    # Use existing helper to send OTP (includes backup email for otp_impaired)
    send_otp(cc, user: @current_user)

    # Mask the destination for security
    masked_path = case cc.path_type
                  when CommunicationChannel::TYPE_SMS
                    # Show last 4 digits of phone number
                    cc.path.gsub(/\d(?=\d{4})/, "*")
                  when CommunicationChannel::TYPE_EMAIL
                    # Mask email (show first char and domain)
                    cc.path.sub(/(?<=.).+(?=@)/, "***")
                  else
                    "***"
                  end

    render json: {
      otp_sent: true,
      channel_type: cc.path_type,
      masked_path:
    }
  end

  def destroy
    user = if params[:user_id] == "self"
             @current_user
           else
             User.find(params[:user_id])
           end
    return unless authorized_action(user, current_principal, :reset_mfa)

    # Determine whose OTP to verify:
    # - If removing your own MFA (or masquerading): verify with that user's code
    # - If admin directly removing another user's MFA: verify with admin's code
    verifying_user = (user == @current_user) ? @current_user : logged_in_user

    if Account.site_admin.feature_enabled?(:require_mfa_verification_for_removal) &&
       verifying_user.otp_secret_key.present?
      verification_code = params[:verification_code]

      unless verification_code.present?
        return render json: { error: t("verification_code_required", "Verification code is required to disable multi-factor authentication") },
                      status: :unprocessable_content
      end

      # Remove spaces from verification code
      verification_code = verification_code.delete(" ")

      # Verify the OTP code against the logged-in user's (not target user's) MFA
      drift = OTP_ALLOWED_DRIFT
      drift = OTP_ALLOWED_DRIFT_SMS if verifying_user.otp_communication_channel_id

      otp_valid = ROTP::TOTP.new(verifying_user.otp_secret_key).verify(verification_code, drift_behind: drift, drift_ahead: drift) ||
                  verifying_user.authenticate_one_time_password(verification_code)

      unless otp_valid
        return render json: { error: t("invalid_verification_code", "Invalid verification code") },
                      status: :unprocessable_content
      end
    end

    user.otp_secret_key = nil
    user.otp_communication_channel = nil
    user.save!
    user.one_time_passwords.scope.delete_all

    render json: {}
  end

  protected

  def send_otp(cc = nil, user: nil)
    user ||= @current_user
    cc ||= user.otp_communication_channel
    key = ROTP::TOTP.new(user_secret_key(user)).now
    cc&.send_otp!(key, @domain_root_account)
    if cc&.otp_impaired?
      user.email_channel&.send_otp!(key, @domain_root_account)
    end
  end

  def secret_key
    user_secret_key(@current_user)
  end

  def user_secret_key(user)
    session[:pending_otp_secret_key] || user.otp_secret_key
  end

  def clear_pending_otp
    session.delete(:pending_otp)
    session.delete(:pending_otp_secret_key)
    session.delete(:pending_otp_communication_channel_id)
  end

  def require_authenticated_user
    return true if @current_user && @current_pseudonym

    render json: { error: "Unauthorized" }, status: :unauthorized
    false
  end

  def increment_statsd(...)
    # ignore
  end
end
