# frozen_string_literal: true

source "https://rubygems.org"

# Specify your gem's dependencies in platform_tokens.gemspec
gemspec

gem "irb"
gem "rake", "~> 13.0"

eval_gemfile("../gemfile_prefix.rb")

gem "rspec", "~> 3.0"
