inherit_from:
  - ../../.rubocop.yml

Layout:
  Enabled: false

Naming:
  Enabled: false

Performance:
  Enabled: false

Rails:
  Enabled: false

Rails/OutputSafety:
  Enabled: true

Style:
  Enabled: false
