inherit_from:
  - ../../.rubocop.yml

Style/PercentLiteralDelimiters:
  Enabled: false
Style/QuotedSymbols:
  EnforcedStyle: double_quotes # because Style/StringLiterals is disabled
Style/StringLiterals:
  Enabled: false
Style/StringLiteralsInInterpolation:
  Enabled: false
