inherit_from:
  - ../../.rubocop.yml

Layout:
  Enabled: false

Style/HashSyntax:
  Enabled: false
Style/PercentLiteralDelimiters:
  Enabled: false
Style/QuotedSymbols:
  EnforcedStyle: double_quotes # because Style/StringLiterals is disabled
Style/RedundantParentheses:
  Enabled: false
Style/SafeNavigation:
  Enabled: false
Style/StringLiterals:
  Enabled: false
Style/StringLiteralsInInterpolation:
  Enabled: false
Style/TernaryParentheses:
  Enabled: false
