name: Circular Dependency Check

on:
  pull_request:
    branches:
      - '*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  depcruise:
    name: Check Circular Dependencies
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Cache Build Output
        uses: actions/cache@v3
        id: cache-build
        with:
          path: packages/*/dist
          key: ${{ runner.os }}-build-${{ hashFiles('**/package.json', 'packages/**') }}

      - name: Build Packages
        if: steps.cache-build.outputs.cache-hit != 'true'
        env:
          NODE_OPTIONS: "--max-old-space-size=4096"
        run: yarn build:packages

      - name: Check Circular Dependencies
        run: yarn depcruise ./ --include-only "^(ui|packages)"
